### ISSUE TITLE
What are the correct training settings for the original Yolov3 and TinyYolov3 (Darknet backbone)

### ISSUE THREAD

**Issue by mvanlierBCG** [david8862/keras-YOLOv3-model-set#34]
I cannot find this information.

Besides this, are there more optimal training settings for the models for this Keras version?

**Comment by david8862** [comment]
> I cannot find this information.
> 
> Besides this, are there more optimal training settings for the models for this Keras version?

Hi @mvanlierBCG , for darknet backbone models, I didn't implement full training from draft since that need backbone training on imagenet. You can do transfer training from existing pretrained weights on other datasets. Following is a sample config cmd for YOLOv3 darknet:

```
# python train.py --model_type=yolo3_darknet --anchors_path=configs/yolo3_anchors.txt --annotation_file=trainval.txt --classes_path=configs/voc_classes.txt --model_image_size=416x416 --multiscale --rescale_interval=50 --learning_rate=0.001 --transfer_epoch=10 --init_epoch=0 --total_epoch=200 --eval_online --eval_epoch_interval=5 --save_eval_checkpoint
```

The training process depends on many factors, so generally there's no optimal training options for all kinds of model type and dataset. The one I attached is just what I always used.
