### ISSUE TITLE
eval about the Trained Nano model(trained on VOC2007), mAP = 17.104 

### ISSUE THREAD

**Issue by johnjunjun7** [david8862/keras-YOLOv3-model-set#6]
1. use the eval.py to evaluate yolov3-tiny.h5(download from the http://pjreddie.com/darknet/yolo/) on VOC2007, the mAP is also very low. 
May be there are some problems with the configuration in the sample code provided by the author, I don't know the function of the parameter--(conf_threshold=0.001) 

2. Using the VOC2007 train the nano has poor performance, maybe we should use the imageNet to train its backbone Network first, then we train it on the VOC or COCO ?
(I want to know how the anthor train the nano Net)

**Comment by david8862** [comment]
1. yolov3-tiny.h5 is trained on COCO dataset with 80 classes, so should not be fit for VOC2007 evaluation which only have 20 classes.
And "conf_threshold" is used to filter the detection result with very low confidence score. The lower this threshold is, the higher mAP result you will get. But that will also lead to plenty of false positive result and very low precision rate (but a higher recall rate). And vise versa. It's caused by the way of mAP metric calculation and you can read this blogpost [mAP (mean Average Precision) for Object Detection](https://medium.com/@jonathan_hui/map-mean-average-precision-for-object-detection-45c121a31173) for more details

2. It's also an untouched but important part in paper, but generally only using VOC2007 to train should not work. I'm also searching & waiting answer :P


> 1. use the eval.py to evaluate yolov3-tiny.h5(download from the http://pjreddie.com/darknet/yolo/) on VOC2007, the mAP is also very low.
>    May be there are some problems with the configuration in the sample code provided by the author, I don't know the function of the parameter--(conf_threshold=0.001)
> 2. Using the VOC2007 train the nano has poor performance, maybe we should use the imageNet to train its backbone Network first, then we train it on the VOC or COCO ?
>    (I want to know how the anthor train the nano Net)

**Comment by johnjunjun7** [comment]
> 1. And "conf_threshold" is used to filter the detection result with very low confidence score. T

Thanks for your explanation  :)

**Comment by david8862** [comment]
I tried to use COCO class label to generate annotation for VOC2007 testset and evaluate yolov3-tiny.h5, got following result:
```
Pascal VOC AP evaluation
person: AP 0.4292, precision 0.0535, recall 0.8163
bicycle: AP 0.5053, precision 0.0612, recall 0.7738
car: AP 0.3175, precision 0.0478, recall 0.7586
motorbike: AP 0.5457, precision 0.0843, recall 0.7805
aeroplane: AP 0.4503, precision 0.0608, recall 0.8521
bus: AP 0.5475, precision 0.0883, recall 0.7283
train: AP 0.5797, precision 0.0798, recall 0.8808
boat: AP 0.2002, precision 0.0371, recall 0.8041
bird: AP 0.3907, precision 0.0707, recall 0.7691
cat: AP 0.6484, precision 0.1362, recall 0.8270
dog: AP 0.4971, precision 0.1267, recall 0.7151
horse: AP 0.5747, precision 0.1054, recall 0.8076
sheep: AP 0.3874, precision 0.0570, recall 0.8296
cow: AP 0.3201, precision 0.0626, recall 0.7568
bottle: AP 0.2013, precision 0.0454, recall 0.5967
chair: AP 0.2626, precision 0.0295, recall 0.7598
sofa: AP 0.4348, precision 0.0764, recall 0.8131
pottedplant: AP 0.2198, precision 0.0395, recall 0.7416
diningtable: AP 0.3917, precision 0.0379, recall 0.7926
tvmonitor: AP 0.3782, precision 0.0868, recall 0.7396
truck: AP 0.0000, precision 0.0000, recall 0.0000
traffic light: AP 0.0000, precision 0.0000, recall 0.0000
...
toothbrush: AP 0.0000, precision 0.0000, recall 0.0000
mAP@IoU=0.50 result: 10.352971
mPrec@IoU=0.50 result: 1.733308
mRec@IoU=0.50 result: 19.428946
```

You only need to check the existing class since the mAP is averaged on all 80 classes. Re-calculated mAP on 20 classes is 41.45

> > 1. And "conf_threshold" is used to filter the detection result with very low confidence score. T

> 
> Thanks for your explanation :)
