### ISSUE TITLE
About yolov5 and data augmentation

### ISSUE THREAD

**Issue by pingchesu** [david8862/keras-YOLOv3-model-set#62]
Hi really thanks for your great implementation of yolo mode!!

Q1:

I recently read about https://blog.roboflow.ai/yolov5-is-here/ this article

Do you consider to implement yolov5?

Q2:

I saw cutmix augmentation have already be implemented in your code, would you suggest use cutmix during training the model?

Really appreciate for your great work!!

**Comment by david8862** [comment]
many thanks.

1. I'm also checking the YOLOv5 code base. But due to YOLOv5 team didn't publish an official paper to describe their new ideas & tricks, it's not easy to get a clear scope of this work. Another concern is YOLOv5 is implemented with PyTorch instead of Darknet framework, so I may have to prepare another tool to convert their pretrained weights to keras model if needed.

2. Actually the cutmix augment function here is just an incidentally practise when I try to add mosaic. But when I almost finish it, I found cutmix may not fit for detector training since it will break bbox like follow(0&1 are image patches, 2 is a bbox on image 0):

              -----------------
              |           0   |
              |   - - -       |
              |  | 2  _|__    |
              |      |    |   |
              |  |   |  1 |   |
              |   -  |____|   |
              |               |
              -----------------

so I didn't involve cutmix in the detector train process. Seems it could just be used in classifier training.
